<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Event;
use Carbon\Carbon;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events = [
            [
                'title' => 'Tech Innovation Summit 2025',
                'description' => 'Join us for the annual Technology Innovation Summit featuring keynote speakers from leading tech companies, workshops on emerging technologies, and networking opportunities with industry professionals.',
                'category' => 'academic',
                'event_date' => Carbon::now()->addDays(15)->setTime(9, 0, 0),
                'event_end_date' => Carbon::now()->addDays(15)->setTime(17, 0, 0),
                'location' => 'Main Auditorium, Building A',
                'organizer' => 'Computer Science Department',
                'capacity' => 200,
                'registered_count' => 45,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'Career Fair Spring 2025',
                'description' => 'Meet with representatives from top companies and explore internship and job opportunities. Bring your resume and dress professionally!',
                'category' => 'career',
                'event_date' => Carbon::now()->addDays(20)->setTime(10, 0, 0),
                'event_end_date' => Carbon::now()->addDays(20)->setTime(16, 0, 0),
                'location' => 'Sports Hall',
                'organizer' => 'Career Services Office',
                'capacity' => 500,
                'registered_count' => 120,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'Entrepreneurship Workshop',
                'description' => 'Learn the fundamentals of starting your own business, pitching to investors, and building a successful startup from experienced entrepreneurs.',
                'category' => 'academic',
                'event_date' => Carbon::now()->addDays(8)->setTime(14, 0, 0),
                'event_end_date' => Carbon::now()->addDays(8)->setTime(18, 0, 0),
                'location' => 'Conference Room 301',
                'organizer' => 'Business Administration Department',
                'capacity' => 50,
                'registered_count' => 32,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'Cultural Festival',
                'description' => 'Celebrate diversity with performances, food stalls, and exhibitions showcasing different cultures from around the world.',
                'category' => 'cultural',
                'event_date' => Carbon::now()->addDays(30)->setTime(12, 0, 0),
                'event_end_date' => Carbon::now()->addDays(30)->setTime(20, 0, 0),
                'location' => 'University Plaza',
                'organizer' => 'Student Affairs',
                'capacity' => 1000,
                'registered_count' => 350,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'AI & Machine Learning Seminar',
                'description' => 'Explore the latest advances in artificial intelligence and machine learning with guest speakers from research institutions and tech companies.',
                'category' => 'academic',
                'event_date' => Carbon::now()->addDays(12)->setTime(13, 0, 0),
                'event_end_date' => Carbon::now()->addDays(12)->setTime(16, 0, 0),
                'location' => 'Lecture Hall 2',
                'organizer' => 'AI Research Lab',
                'capacity' => 100,
                'registered_count' => 78,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'Annual Sports Day',
                'description' => 'Join us for a day of sports competitions, including football, basketball, volleyball, and track & field events.',
                'category' => 'sports',
                'event_date' => Carbon::now()->addDays(25)->setTime(8, 0, 0),
                'event_end_date' => Carbon::now()->addDays(25)->setTime(18, 0, 0),
                'location' => 'University Stadium',
                'organizer' => 'Sports Department',
                'capacity' => 800,
                'registered_count' => 245,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'Data Science Bootcamp',
                'description' => 'Intensive 3-day workshop covering data analysis, visualization, and machine learning fundamentals. Perfect for beginners and intermediate learners.',
                'category' => 'academic',
                'event_date' => Carbon::now()->addDays(35)->setTime(9, 0, 0),
                'event_end_date' => Carbon::now()->addDays(37)->setTime(17, 0, 0),
                'location' => 'Computer Lab 1',
                'organizer' => 'Data Science Club',
                'capacity' => 40,
                'registered_count' => 38,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'International Food Festival',
                'description' => 'Taste authentic cuisines from around the world! Featuring food stalls from different countries and cultural performances.',
                'category' => 'cultural',
                'event_date' => Carbon::now()->addDays(45)->setTime(11, 0, 0),
                'event_end_date' => Carbon::now()->addDays(45)->setTime(22, 0, 0),
                'location' => 'University Courtyard',
                'organizer' => 'International Students Association',
                'capacity' => 600,
                'registered_count' => 180,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'Mental Health Awareness Week',
                'description' => 'A series of workshops and seminars focused on mental health, stress management, and well-being. Free counseling sessions available.',
                'category' => 'social',
                'event_date' => Carbon::now()->addDays(50)->setTime(10, 0, 0),
                'event_end_date' => Carbon::now()->addDays(56)->setTime(16, 0, 0),
                'location' => 'Student Center',
                'organizer' => 'Student Wellness Center',
                'capacity' => 150,
                'registered_count' => 95,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'Blockchain & Cryptocurrency Conference',
                'description' => 'Learn about blockchain technology, cryptocurrency trading, and the future of decentralized finance from industry experts.',
                'category' => 'academic',
                'event_date' => Carbon::now()->addDays(60)->setTime(9, 30, 0),
                'event_end_date' => Carbon::now()->addDays(60)->setTime(17, 30, 0),
                'location' => 'Main Auditorium',
                'organizer' => 'Finance & Technology Club',
                'capacity' => 300,
                'registered_count' => 156,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'Art & Design Exhibition',
                'description' => 'Showcase of student artwork, photography, and design projects. Vote for your favorite pieces and network with fellow artists.',
                'category' => 'cultural',
                'event_date' => Carbon::now()->addDays(18)->setTime(14, 0, 0),
                'event_end_date' => Carbon::now()->addDays(18)->setTime(20, 0, 0),
                'location' => 'Art Gallery',
                'organizer' => 'Art Department',
                'capacity' => 200,
                'registered_count' => 67,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'Environmental Sustainability Workshop',
                'description' => 'Hands-on workshop on sustainable living, recycling initiatives, and campus environmental projects. Join our green movement!',
                'category' => 'social',
                'event_date' => Carbon::now()->addDays(22)->setTime(15, 0, 0),
                'event_end_date' => Carbon::now()->addDays(22)->setTime(18, 0, 0),
                'location' => 'Environmental Center',
                'organizer' => 'Green Campus Initiative',
                'capacity' => 80,
                'registered_count' => 52,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'Alumni Networking Mixer',
                'description' => 'Connect with successful alumni from various industries. Great opportunity for career advice and professional networking.',
                'category' => 'career',
                'event_date' => Carbon::now()->addDays(28)->setTime(18, 0, 0),
                'event_end_date' => Carbon::now()->addDays(28)->setTime(21, 0, 0),
                'location' => 'Grand Ballroom',
                'organizer' => 'Alumni Association',
                'capacity' => 150,
                'registered_count' => 89,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'Music & Talent Show',
                'description' => 'Annual talent show featuring student musicians, singers, dancers, and performers. Come support your fellow students!',
                'category' => 'cultural',
                'event_date' => Carbon::now()->addDays(40)->setTime(19, 0, 0),
                'event_end_date' => Carbon::now()->addDays(40)->setTime(23, 0, 0),
                'location' => 'Theater Hall',
                'organizer' => 'Entertainment Club',
                'capacity' => 400,
                'registered_count' => 178,
                'is_active' => true,
                'image_url' => null,
            ],
            [
                'title' => 'Cybersecurity Awareness Seminar',
                'description' => 'Learn about online safety, password security, phishing prevention, and best practices for protecting your digital life.',
                'category' => 'academic',
                'event_date' => Carbon::now()->addDays(32)->setTime(11, 0, 0),
                'event_end_date' => Carbon::now()->addDays(32)->setTime(14, 0, 0),
                'location' => 'Cybersecurity Lab',
                'organizer' => 'IT Security Department',
                'capacity' => 120,
                'registered_count' => 73,
                'is_active' => true,
                'image_url' => null,
            ],
        ];

        foreach ($events as $eventData) {
            Event::create($eventData);
        }

        $this->command->info('Events seeded successfully!');
    }
}
